name: GitHub-Profile-Summary-Cards

on:
  schedule: # 毎日UTC 0:00に更新
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-summary-cards
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: vn7n24f1tk/github-profile-summary-cards@v2.3.1
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          target_branch: main
          repository: Ubichinon/Ubichinon
