name: Waka Readme
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
permissions:
  contents: write
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: anmol098/waka-readme-stats@master # 参照先を anmol098 に変更
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_TITLE: true
          SECTION_NAME: waka
          BLOCKS: ░▒▓█
          TIME_RANGE: last_7_days
          SHOW_TIME: true
          SHOW_MASKED_TIME: true
